import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "../components/layout";
import { Provider } from "react-redux";
import store from "../store/store";
import ClientProvider from "./clientProvider";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});

export const metadata = {
  title: "Chuly App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans  w-[100w] bg-[#F6F6F6]`}
      >
        <ClientProvider>
            <Layout>
                {children}
            </Layout>
        </ClientProvider>
      </body>
    </html>
  );
}
